{ options, config, lib, pkgs, ... }:

with lib;
with lib.my;
let
  cfg = config.modules.desktop.apps.flatpak;
  flatpakInit = "flatpak-init";
in {
  options.modules.desktop.apps.flatpak = with types; {
    enable = mkBoolOpt false;
    apps = mkOpt' attrs { } ''
      Attrset of app names and flatpak app ID's that should be added to the `${flatpakInit}` helper script.
    '';
  };

  config = mkIf cfg.enable {
    xdg.portal.enable = true;
    services.flatpak.enable = true;

    user.packages = let
      apps = concatStringsSep " " (attrValues cfg.apps);
      appInstallLine =
        if apps != "" then "flatpak install flathub ${apps}" else "";
    in with pkgs;
    # Add init script.
    [
      (writeScriptBin flatpakInit ''
        #!${stdenv.shell}

        # This was auto-generated by the nix-configuration, do not edit manually!

        # Add flathub remote.
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        # Install given apps.
        ${appInstallLine}
      '')
    ] ++
    # Add `flatpak run` wrappers for apps.
    (mapAttrsToList (appName: appId:
      (writeScriptBin appName ''
        #!${stdenv.shell}
        exec flatpak run ${appId}
      '')) cfg.apps);
  };
}
