context.modules = [
  {
    name = libpipewire-module-echo-cancel
    args = {
      # library.name  = aec/libspa-aec-webrtc
      # node.latency = 1024/48000
      # monitor.mode = false
      #
      # .--------.     .---------.     .--------.     .----------.     .-------.
      # |  mic   | --> | capture | --> |        | --> |  source  | --> |  app  |
      # '--------'     '---------'     | echo   |     '----------'     '-------'
                                     # | cancel |
      # .--------.     .---------.     |        |     .----------.     .---------.
      # |  app   | --> |  sink   | --> |        | --> | playback | --> | speaker |
      # '--------'     '---------'     '--------'     '----------'     '---------'
      capture.props = {
        # A capture that captures audio from a microphone.
        node.name = "Echo Cancellation Capture"
        node.description = "Microphone Capture"
      }
      sink.props = {
        # Sink containing the data that should be canceled out from the capture
        # stream. This is where applications send audio to.
        node.name = "Echo Cancellation Sink"
        node.description = "Audio stream to cancel out"
      }
      playback.props = {
        # Playback that passes the signal from the sink to the speaker so that
        # you hear applications.
        node.name = "Echo Cancellation Playback"
        node.description = "Output to speakers"
      }
      source.props = {
        # Source that exposes the echo-canceled data captured from the capture
        # stream. The data from the sink stream and capture stream are
        # correlated and the signal from the sink stream is removed from the
        # capture stream data. This data then goes into applications and does
        # not contain the echo from the playback.
        node.name = "Echo Cancellation Source"
        node.description = "Echo canceled input source"
      }
    }
  }
]
