[bar.default]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "battery",
    "control-center"
]
margin_ends = 800
position = "bottom"
start = [ "workspaces" ]

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 20

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[location]
address = "Stockholm, Sweden"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 1920.0
    cy = 1427.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 384.0
    cx = 1920.0
    cy = 984.0
    output = "DP-2"
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 144.0
    box_width = 288.0
    cx = 1920.0
    cy = 1152.0
    output = "DP-2"
    rotation = 0.0
    type = "weather"

[shell]
font_family = "SF Pro Text"

[theme]
builtin = "Noctalia"
community_palette = "One Dark Two"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "muted"

[wallpaper]
directory = "/home/love/Pictures"

    [wallpaper.default]
    path = "/home/love/Pictures/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/love/Pictures/wallpaper.jpg"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false
