[[profile]]
name = "laptop"
exec = [
    "notify-send shikane \"Applied profile $SHIKANE_PROFILE_NAME\""
]

[[profile.output]]
enable = true
search = ["n=eDP-1"]
mode = "1920x1200@60.026Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "work-dual-external-1"
exec = [
    "notify-send shikane \"Applied profile $SHIKANE_PROFILE_NAME\"",
    """
    hyprctl --batch \"
        dispatch moveworkspacetomonitor 1 DP-5;
        dispatch moveworkspacetomonitor 2 DP-5;
        dispatch moveworkspacetomonitor 3 DP-6;
        dispatch moveworkspacetomonitor 4 DP-6;
        dispatch moveworkspacetomonitor 5 eDP-1;
        dispatch moveworkspacetomonitor 10 eDP-1
        \"
    """
]

[[profile.output]]
enable = true
search = ["n=eDP-1"]
mode = "1920x1200@60.026Hz"
position = "1637,1440"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["n=DP-5"]
mode = "2560x1440@59.951Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["n=DP-6"]
mode = "2560x1440@59.951Hz"
position = "2560,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "work-dual-external-2"
exec = [
    "notify-send shikane \"Applied profile $SHIKANE_PROFILE_NAME\"",
    """
    hyprctl --batch \"
        dispatch moveworkspacetomonitor 1 DP-7;
        dispatch moveworkspacetomonitor 2 DP-7;
        dispatch moveworkspacetomonitor 3 DP-8;
        dispatch moveworkspacetomonitor 4 DP-8;
        dispatch moveworkspacetomonitor 5 eDP-1;
        dispatch moveworkspacetomonitor 10 eDP-1
        \"
    """
]

[[profile.output]]
enable = true
search = ["n=eDP-1"]
mode = "1920x1200@60.026Hz"
position = "1637,1440"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["n=DP-7"]
mode = "2560x1440@59.951Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["n=DP-8"]
mode = "2560x1440@59.951Hz"
position = "2560,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "home_tv"
exec = [
    "notify-send shikane \"Applied profile $SHIKANE_PROFILE_NAME\""
]

[[profile.output]]
enable = true
search = ["n=HDMI-A-1"]
mode = "3840x2160@60Hz"
position = "1920,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["n=eDP-1"]
mode = "1920x1200@60.026Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Work 4K"
exec = [
    "notify-send shikane \"Applied profile $SHIKANE_PROFILE_NAME\""
]

[[profile.output]]
enable = true
search = ["n=DP-3"]
mode = "3840x2160@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["n=eDP-1"]
mode = "1920x1200@60.026Hz"
position = "960,2160"
scale = 1.0
transform = "normal"
adaptive_sync = false
