monitor.alsa.rules = [

  # DEVICES

  {
    matches: [
      {
        device.nick: "HDA ATI HDMI"
      }
    ]
    actions: {
      update-props: {
        device.disabled: true
      }
    }
  }
  {
    matches: [
      {
        device.nick: "HD-Audio Generic"
      }
    ]
    actions: {
      update-props: {
        device.disabled: true
      }
    }
  }

  # SINKS

  {
    matches: [
      {
        node.description: "USB Audio Speakers"
      }
    ],
    actions: {
      update-props: {
        # Up the priority so that it is chosen as the default output.
        priority.driver: 1110
        priority.session: 1110
        # Set a more descriptive nick and description.
        node.nick: "Headphones" # "USB Audio" by default.
        node.description: "Headphones"
      }
    }
  }
  {
    matches: [
      {
        node.description: "USB Audio S/PDIF Output"
      }
    ],
    actions: {
      update-props: {
        node.disabled: true
      }
    }
  }
  {
    matches: [
      {
        node.description: "USB Audio Front Headphones"
      }
    ],
    actions: {
      update-props: {
        node.disabled: true
      }
    }
  }

  # SOURCES

  {
    matches: [
      {
        node.description: "RODE NT-USB Analog Stereo"
      }
    ],
    actions: {
      update-props: {
        # Up the priority so that it is chosen as the default output.
        priority.driver: 2110
        priority.session: 2110
      }
    }
  }
  {
    matches: [
      {
        node.description: "USB Audio Microphone"
      }
    ],
    actions: {
      update-props: {
        node.disabled: true
      }
    }
  }
  {
    matches: [
      {
        node.description: "USB Audio Line Input"
      }
    ],
    actions: {
      update-props: {
        node.disabled: true
      }
    }
  }
]
