ipc = off

# preload = ~/Pictures/wallpapers/Cluster/contents/images/3840x2160.png
# wallpaper = ,~/Pictures/wallpapers/Cluster/contents/images/3840x2160.png

preload = ~/Pictures/wallpapers/MilkyWay/contents/images/5120x2880.png
wallpaper = ,~/Pictures/wallpapers/MilkyWay/contents/images/5120x2880.png
