# monitor.bluez.rules = [
#   {
#     matches = [
#       {
#         device.name = "bluez_card.*"
#       }
#     ]
#   }
# ]

monitor.bluez.properties = {
  bluez5.headset-roles = [ hsp_hs hfp_hf ]
}
